spring:
  datasource:
    url: ${MYSQL_URL_AZURE}
    username: ${MYSQL_USERNAME_AZURE}
    password: ${MYSQL_PASSWORD_AZURE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

auth:
  token:
    expirationinMils: 3600000
    jwtSecret: ${JWT_SECRET}