spring.application.name=hotel-api

# Configuración básica de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hoteleria
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

