spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.hibernate.SQL: DEBUG  # Para ver las consultas SQL en el log
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Para ver los parámetros de las consultas

auth:
  token:
    expirationinMils: 3600000
    jwtSecret: ${JWT_SECRET}
