spring:
  datasource:
    url: jdbc:mysql://db-hotel-mysql.mysql.database.azure.com:3306/db_hotel
    username: mysql_admin
    password: Superadmin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    out-of-order: true
    url: jdbc:mysql://db-hotel-mysql.mysql.database.azure.com:3306/db_hotel
    user: mysql_admin
    password: Superadmin123
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.flywaydb: DEBUG
auth:
  token:
    expirationinMils: 3600000
    jwtSecret: 12345678910QPWLEOAIMZNCHDJSKLQIWURHT102OAPZLFMAKQIWU12049586J23MAMZJ18234
azure:
  storage:
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=imageneshoteleria;AccountKey=5oseUg+aILzsVpCBfkgaZ7Lq70M+/DHBYKpNOil8nbyU/vmDajSyBM4lY3BkRXy5QBpBLs987aHd+AStbjeYkA==;EndpointSuffix=core.windows.net
    container:
      name: imagenes-usuarios
app:
  mail:
    password: wzcm dmfo pptv ooit
    user: josuealva920@gmail.com