name: Build and deploy JAR app to Azure Web App - hoteleria
on:
  push:
    branches:
      - kayron
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: Build with Maven
        run: mvn clean install -DskipTests    # Modificado aquí para saltar las pruebas
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    env:
      JWT_SECRET: '12345678910QPWLEOAIMZNCHDJSKLQIWURHT102OAPZLFMAKQIWU12049586J23MAMZJ18234'
      MYSQL_PASSWORD_AZURE: 'Superadmin123'
      MYSQL_URL_AZURE: 'jdbc:mysql://db-hotel-mysql.mysql.database.azure.com:3306/db_hotel'
      MYSQL_USERNAME_AZURE: 'mysql_admin'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4F2347D108C74B5C8A2184E797B8E274 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB7CCE3E661A472586CD81BAD9290C3D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08A4596A9A6347AAB3F47A8FEF446B3E }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hoteleria'
          slot-name: 'Production'
          package: '*.jar'
